- name: Storage 
  hosts: all
  vars: 
    vcenter_hostname: 172.37.7.10
    vcenter_username: Administrator@vsphere.local
    vcenter_password: Hitachi1!
    datastore_name: Test
    vmfs_device_name: mpx.vmhba1:C0:T2:L0
    datastore_type: vmfs
    esxi_hostname: 172.37.7.15
    datacenter_name: vlab-phuc-02
    cluster_name: cluster-01
    esxi_username: root
    esxi_password: Hitachi1!


  tasks:
    - name: Create Datacenter
      community.vmware.vmware_datacenter:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ datacenter_name }}'
        state: present
        validate_certs: no
      delegate_to: localhost

    - name: Create Cluster
      community.vmware.vmware_cluster:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ datacenter_name }}'
        cluster_name: '{{ cluster_name }}'
        validate_certs: no
      delegate_to: localhost

    - name: Add ESXi Host to vCenter
      community.vmware.vmware_host:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter: '{{ datacenter_name }}'
        cluster: '{{ cluster_name }}'
        esxi_hostname: '{{ esxi_hostname }}'
        esxi_username: '{{ esxi_username }}'
        esxi_password: '{{ esxi_password }}'
        state: present
        validate_certs: yes
      delegate_to: localhost  

    - name: Recan HBA's for a given ESXi host and refresh storage system objects
      community.vmware.vmware_host_scanhba:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          esxi_hostname: '{{ esxi_hostname }}'
          refresh_storage: true
          validate_certs: no
      delegate_to: localhost

    - name: Mount VMFS datastores to ESXi
      community.vmware.vmware_host_datastore:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          datastore_name: '{{ datastore_name }}'
          datastore_type: '{{ datastore_type }}'
          vmfs_device_name: '{{ vmfs_device_name }}'
          vmfs_version: 6
          esxi_hostname: '{{ esxi_hostname }}'
          validate_certs: no
          state: present
      delegate_to: localhost

      # - name: Gather info from standalone ESXi server having datacenter as 'ha-datacenter'
      #   community.vmware.vmware_datastore_info:
      #     hostname: '172.37.7.15'
      #     username: 'root'
      #     password: 'Hitachi1!'
      #     datacenter_name: "vlab-phuc"
      #     validate_certs: no
      #   delegate_to: localhost
      #   register: info

      # - name: Print info
      #   ansible.builtin.debug:
      #     var: info
