- name: Storage 
  hosts: all
  vars: 
    vcenter_hostname: https://172.37.7.10/
    vcenter_username: Administrator@vsphere.local
    vcenter_password: Hitachi1!
    datastore_name: mpx.vmhba1:C0:T1:L0
    datastore_type: vmfs
    inventory_hostname: https://172.37.7.15/
  tasks:
    # - name: Create Datacenter
    #   community.vmware.vmware_datacenter:
    #     hostname: '{{ vcenter_hostname }}'
    #     username: '{{ vcenter_username }}'
    #     password: '{{ vcenter_password }}'
    #     datacenter_name: '{{ datacenter_name }}'
    #     state: present
    #   delegate_to: localhost

    - name: Mount VMFS datastores to ESXi
      community.vmware.vmware_host_datastore:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          datastore_name: '{{ datastore_name }}'
          datastore_type: '{{ datastore_type }}'
          vmfs_device_name: '{{ inventory_hostname }}'
          vmfs_version: 5
          esxi_hostname: '{{ inventory_hostname }}'
          state: present
      delegate_to: localhost