- name: Demo 
  hosts: all
  
  tasks:
    # - name: Install unzip
    #   apt:
    #     name: unzip
    #     state: absent
    - name: Template a file to /homes/playbooks/result.txt
      ansible.builtin.template:
        src: test.txt
        dest: /homes/playbooks/result.txt
        owner: bin
        group: wheel
        mode: '0644'