- name: Demo 
  hosts: all
  become: yes
  become_user: root
  
  tasks:
    # - name: Install unzip
    #   apt:
    #     name: unzip
    #     state: absent
    - name: Template a file to /home/playbooks/result.txt
      ansible.builtin.template:
        src: test.txt
        dest: /home/playbooks/result.txt
        owner: root
        group: root
        mode: '0644'