- name: Demo 
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  become_ask_pass: false
  #become_ask_pass = true
  remote_user: hiopadmin
  
  tasks:
    # - name: Install unzip
    #   apt:
    #     name: unzip
    #     state: absent
    - name: Template a file to /home/playbooks/result.txt
      ansible.builtin.template:
        src: test.txt
        dest: /home/playbooks/result.txt
        owner: bin
        group: wheel
        mode: '0644'